project:
  type: website
  output-dir: docs

website:
  title: "Josh Knecht"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: docs/CV.pdf
        text: CV
        target: _blank
      - icon: github
        href: https://github.com/knechtthedots
        target: _blank
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

